# Generated by Django 4.1.2 on 2022-10-17 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_profile_alter_gender_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='username',
        ),
        migrations.AddField(
            model_name='gender',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genders', to=settings.AUTH_USER_MODEL),
        ),
    ]
